# Travis CI config for Debspawn

language: python
dist: bionic
sudo: required
arch:
  - amd64
  - ppc64le

addons:
  apt:
    update: true
    packages:
    - xsltproc
    - docbook-xsl
    - docbook-xml
    - zstd
    - systemd-container
    - debootstrap

python:
  - "3.7"
  - "3.8"
  - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

install:
 - pip install flake8 pytest

script:
  - ./setup.py build
  - ./setup.py install --single-version-externally-managed --root=/tmp
  - sudo $(which python3) -m pytest
  - rm -rf build/
  - flake8 ./
  - flake8 debspawn/dsrun
